import Head from "next/head";

const HeaderInfo = () => {
  return (
    <Head>
      <title>FindBooks</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Noto+Sans+KR:wght@400;500;700&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
};

export default HeaderInfo;
